## Discrete states of DNA

In [ ]:
# AGCT, transversions and transitions. Please consider that transitions in biological terms is different to transition in probabilistic terms.

In [307]:
import toyplot
import itertools
import random

edges = [i for i in itertools.permutations('ACGT', r=2)]
transitions = {("A","G"),("C","T")}
colors = []
for e in edges:
    sorted_e = tuple(sorted(list(e)))
    if sorted_e in transitions:
        colors.append("blue")
    else:
        colors.append("red")

        
canvas, axes, graph = toyplot.graph(
        [i[0] for i in edges],
        [i[1] for i in edges],
        ecolor=colors,
        ewidth=5,
        eopacity=0.35,
        width=350,
        height=350,
        margin=0,
        tmarker=">", 
        vsize=50,
        vcoordinates=[(-1,1),(-1,-1),(1,1), (1,-1)],
        vstyle={"stroke": "black", "stroke-width": 2, "fill": "none"},
        vlstyle={"font-size": "20px"},
        layout=toyplot.layout.FruchtermanReingold(edges=toyplot.layout.CurvedEdges())
)

f_style = {"font-size": "14px"} 
canvas.text(175,40, "Transitions", style=f_style)
canvas.text(175,310, "Transitions", style=f_style)
canvas.text(40,175, "Transversions", angle=90, style=f_style)
canvas.text(175,175, "Transversions", style=f_style)
canvas.text(310,175, "Transversions", angle=270, style=f_style);

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="350.0px" height="350.0px" viewBox="0 0 350.0 350.0" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="t6b2a97af577b46b2b451836fbf7cb6e0"> A C G T Transitions Transitions Transversions Transversions Transversions

These discrete state can be modelled by Markov chains

## Markov chains

<div class="markov">
  <iframe width="800" height="500" src="https://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0.5%2C0.2%2C0.1%2C0.2%5D%2C%5B0.1%2C0.5%2C0.3%2C0.1%5D%2C%5B0.05%2C0.2%2C0.7%2C0.05%5D%2C%5B0%2C0.05%2C0.05%2C0.9%5D%5D%7D"></iframe>
</div>

- parts of a markov chain
- property (memory-less)
- stationary distributuon or squilibrion state or simple pi


 is a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event


markov property Markov property refers to the memoryless property of a stochastic process. 

Graph

procesar:
    

for some:  Markov chain or Markov process  are synonyms


A next-state stochastic process variable, dependent only on 
the current state, with the property of "forgetting" all states 
before, has the Markov property.


Markov process
A continuous stochastic process with the Markov property is 
called a Markov process. The probability of change from 
one state to the subsequent state is governed by a 
Markov propagator.


Markov chain
A discrete process with the Markov property is called a 
Markov chain. The probability of change from one state to 
the subsequent state is called the transition probability.

In [ ]:
# a graph lke the previous one can be represented in a matrix like the following

In [2]:
import numpy as np

In [308]:
                               #  A     C     G     T
transition_matrix = np.array([[0.50, 0.20, 0.10, 0.20],  # A
                              [0.10, 0.50, 0.30, 0.10],  # C
                              [0.05, 0.20, 0.70, 0.05],  # G
                              [0.00, 0.05, 0.05, 0.90]   # T
                             ])

using the transition probabilities in this matrix we can do a random walk changing from one state to another a given number of steps (time)

In [12]:
def print_random_walk(states, steps, initial_state, transition_matrix):
    current_state = initial_state
    result_sequence = [current_state]

    step = 1
    while step < steps:
        previous_state = current_state
        previous_idx = states.index(previous_state)
        
        # Choice one random base on the probabilities on the matrix picking the previous row 
        current_state = np.random.choice(list(states), p=transition_matrix[previous_idx])
        result_sequence.append(current_state)
        step += 1
    
    return "".join(result_sequence)

In [309]:
sequence = print_random_walk(states="ACGT", 
                  steps=100, 
                  initial_state="G", 
                  transition_matrix=transition_matrix)

sequence

'GGGGGGTTCCCACCTTTTTTTTCCGGGGGGGTTTTTTCCCGGGGGGACCCTTTTTTTTTTTTTTGGGGGGGGAGGCCTTTTTTTTTTTTCCGGGCCCTTT'

We can notice that this random walk generated some patterns in the sequence, these patterns are influenced by the transition probabilities in a Markov model because as we mentioned before, the probability of have a given future state depends of the previous state.

At some point this distribution, even being random, some patterns are predictable. We can predict, for example, how many T's are expected in a sequence given a set of transition probabilities.

That predictability is represented by the stationary distribution or equilibrium in a Markov model. 


### Stationary distributions or Equilibrium

This is commonly called pi

In [310]:
# we can see how distributuon of each base if converging and it will not change with time (steps)
sequence = print_random_walk(states="ACGT", 
                  steps=1000, 
                  initial_state="G", 
                  transition_matrix=transition_matrix)
sequence

'GGTCTTGGGGGGGCCCCCCCGGGACTTTTCCAAAGAAAAGGGGGTTTTTTTTTTTTTTTTTGCATTTTCCCAATTTTTTTTTTTTTCCCAAAAAGGCCCCGGATTCCGAAAAAACCTTTTTTTTTTTTTTTTTTTTTTTTTTGCCACCCCCGGCGGGCGGTTTTTTTTTTTTTTGCCCCGCTTTTTTTTTTTTTTCTTTTTTTTTTTGGGGCGGGGGGCCGGGGGCATTTTTTTTTTCCGGGCGCCAAAGGGGGCGGGGCCCCGGCTTTTTTTTTTTTTTTTTTTTGCGATTTTTGGCCAATTTGGGCGGAGACCCCCTTTTTTTTTGGGGCCCGGGCCATTTTTGGGGGGGGCGGGGGCACAAAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTGGGTTTTTTGGCCCCAGCCCTTTGGGGTTTTTTTTTTTCGGGGGGGCCCGCCGGGGGGGGCCGCTTTTTTTTCTCCTTTTTTTTTCAATTTTCCCAACCGGGATCCCGTTTCCGGCAAACGGGGTTTTCCCCCCCCCGGCTTGATCCCCTTTGGCCCTTTTTCCGGGGGGGTTTTTTTTGCCGGGGGGGCCACGGGCCCCCCAACGGCCCACCCCCCTTTTTTTTTTCCCGGGCTTTTTTTTTTTTTTGCCCTTTTTTTTTTCCCGGGGCCCGGGACCGCCGGGGCCCCCCTCTTTTTTTTCAACCCGTTTTTTTTTTTTTTTTTTTTTTTTCCGCAGCCAATTTTTTTTTTTTTTTTTTTTTTTTTGGGCCCGGCGAAATTTTTTTTTTTTTTTTTTTCATTGGGGCCCTTTTTTTCCCGGGCCCGGGGGCCCCGGTTTTTTTTGGGGGAAACAAATTGAAATTTTTTTTTTTTTTTTTTTTTTTCCGGGGGGGGGGGGGGCCCCTTTGCCGGGGCGCCCGGGGGCTTTTTTTTCTTTTTGGGCCGACCCGCGGGCCAATTCCCTTGGGGGGCCAATTTTTCGGGGGGGCACCCCCGGGGGCG

In [311]:
empiric_frequencies = {}
for base in "ACGT":
    empiric_frequencies[base] = sequence.count(base) / len(sequence)
    
empiric_frequencies  

{'A': 0.079, 'C': 0.233, 'G': 0.253, 'T': 0.435}

let me illustrate that with a plot

In [183]:
import toyplot

def plot_convergency(states, steps, initial_state, transition_matrix):

    current_state = initial_state
    sequence = [current_state]
    empiric_frequencies = np.zeros((int(steps), len(states))) 

    step = 1
    while step < steps:
        previous_state = current_state
        previous_idx = states.index(previous_state)

        current_state = np.random.choice(list(states), p=transition_matrix[previous_idx])
        sequence.append(current_state)

        step_freq = []
        for base in states:
            step_freq.append(sequence.count(base) / len(sequence))

        empiric_frequencies[step] = step_freq
        step += 1


    label_style = {"text-anchor":"start", "-toyplot-anchor-shift":"5px"}
    canvas, axes, mark = toyplot.plot(empiric_frequencies)

    for i in states:
        axes.text(steps, empiric_frequencies[-1,states.index(i)], i, style=label_style)
    
    return canvas, axes, mark

In [312]:
plot_convergency(states="ACGT", initial_state="A", steps= 10000, transition_matrix=transition_matrix);

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="600px" height="600px" viewBox="0 0 600 600" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="t6b6c24738f5246fab010d1b1139fd8e2"> <path d="M 50.0 550.0 L 50.04860635848939 50.0 L 50.09721271697879 50.0 L 50.145819075468175 175.0 L 50.19442543395756 250.0 L 50.243031792446956 300.0 L 50.29163815093635 335.7142857142857 L 50.340244509425744 362.5 L 50.38885086791514 383.33333333333337 L 50.43745722640453 400.0 L 50.48606358489392 413.6363636363636 L 50.534669943383314 425.0 L 50.58327630187271 434.6153846153846 L 50.6318826603621 442.85714285714283 L 50.68048901885149 450.0 L 50.729095377340876 456.25 L 50.77770173583028 461.7647058823529 L 50.826308094319664 466.6666666666667 L 50.87491445280906 471.05263157894734 L 50.92352081129845 475.0 L 50.972127169787846 478.5714285714286 L 51.02073352827723 481.8181818181818 L 51.069339886766635 484.7826086956522 L 51.11794624525602 466.6666666666667 L 51.16655260374541 470.0 L 51.2151589622348 473.07692307692304 L 51.2637653207242 475.9259259259259 L 51.312371679213584 478.5714285714286 L 51.36097803770298 481.03448275862064 L 51.40958439619237 483.33333333333337 L 51.45819075468176 485.48387096774195 L 51.50679711317115 487.5 L 51.555403471660554 489.3939393939394 L 51.60400983014994 491.17647058823525 L 51.652616188639335 492.85714285714283 L 51.70122254712872 494.4444444444444 L 51.749828905618116 495.94594594594594 L 51.79843526410751 497.36842105263156 L 51.8470416225969 498.71794871794873 L 51.8956479810863 487.5 L 51.944254339575686 476.8292682926829 L 51.99286069806507 478.5714285714286 L 52.04146705655447 480.2325581395349 L 52.09007341504386 481.8181818181818 L 52.138679773533255 483.33333333333337 L 52.18728613202265 484.7826086956522 L 52.23589249051204 486.1702127659575 L 52.28449884900143 487.5 L 52.333105207490824 488.77551020408157 L 52.38171156598022 490.0 L 52.430317924469605 491.17647058823525 L 52.478924282959 492.3076923076923 L 52.52753064144839 493.39622641509436 L 52.57613699993778 485.18518518518516 L 52.624743358427175 477.27272727272725 L 52.67334971691656 469.64285714285717 L 52.72195607540596 471.05263157894734 L 52.77056243389536 472.4137931034483 L 52.819168792384744 473.728813559322 L 52.86777515087414 475.0 L 52.91638150936353 476.2295081967213 L 52.96498786785292 477.4193548387097 L 53.01359422634232 478.5714285714286 L 53.06220058483171 479.6875 L 53.110806943321094 480.7692307692308 L 53.15941330181049 481.8181818181818 L 53.20801966029988 482.83582089552243 L 53.25662601878927 483.82352941176475 L 53.305232377278664 484.7826086956522 L 53.353838735768065 485.7142857142857 L 53.40244509425745 486.61971830985914 L 53.451051452746846 487.5 L 53.49965781123623 488.35616438356163 L 53.54826416972563 489.1891891891892 L 53.59687052821502 490.0 L 53.64547688670441 490.7894736842105 L 53.6940832451938 491.55844155844153 L 53.742689603683196 492.3076923076923 L 53.79129596217258 493.03797468354435 L 53.83990232066198 493.75 L 53.88850867915137 494.4444444444444 L 53.937115037640766 495.1219512195122 L 53.98572139613015 495.7831325301205 L 54.034327754619554 496.42857142857144 L 54.08293411310894 497.0588235294118 L 54.131540471598335 497.6744186046512 L 54.18014683008773 498.2758620689655 L 54.228753188577116 498.8636363636364 L 54.27735954706651 499.438202247191 L 54.3259659055559 500.0 L 54.37457226404529 500.54945054945057 L 54.423178622534685 501.0869565217391 L 54.47178498102407 501.6129032258064 L 54.52039133951347 502.12765957446805 L 54.56899769800286 502.63157894736844 L 54.617604056492254 503.125 L 54.66621041498165 503.6082474226804 L 54.714816773

we can find this Stationary distribution using different approach, two very simple approachs are :


In [162]:
def get_stationary_dist_monte_carlo(states, steps, initial_state, transition_matrix):
    # Create empty array to put the frequency of a given state
    frequencies = np.zeros(len(states)) 
    
    # do first step
    initial_idx = states.index(initial_state)
    frequencies[initial_idx] = 1
    previous_idx = initial_idx
    
    # do other steps
    step = 1
    while step < steps:
        current_state = np.random.choice(list(states), p=transition_matrix[previous_idx])
        current_idx = states.index(current_state)
        frequencies[current_idx] += 1
        previous_idx = current_idx
        step += 1
    
    stationary_distribution = frequencies / steps   # π
    return stationary_distribution


In [163]:
get_stationary_dist_monte_carlo(states="ACGT", 
                          steps=1e6, 
                          initial_state="A", 
                          transition_matrix=transition_matrix)

array([0.065744, 0.185359, 0.284671, 0.464226])

In [165]:
def get_stationary_dist_matrix_multiplication(states, iterations, transition_matrix):
    """Repeated matrix multiplication method"""
    current_matrix = transition_matrix
    
    iteration = 1
    while iteration < iterations:
        # Calculate the Matrix product of two arrays
        current_matrix = np.matmul(current_matrix, transition_matrix)
        iteration += 1
    
    stationary_distribution = current_matrix[0]
    return stationary_distribution

In [313]:
get_stationary_dist_expo("ACGT", iterations=100, transition_matrix=transition_matrix)

array([0.06593407, 0.18681319, 0.28571429, 0.46153846])

## Homology in alignments

In [ ]:
# reminder about homology in molecular world

<html>
<head>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>Ind.</th>
				<th>N1</th>
				<th>N2</th>
				<th>N3</th>
				<th>N4</th>
				<th>N5</th>
				<th>N6</th>
				<th>N7</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Ind. 1</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#FC8D62;">C</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
			</tr>
			<tr>
				<td>Ind. 2</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
			</tr>
			<tr>
				<td>Ind. 3</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
			</tr>
			<tr>
				<td>Ind. 4</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
			</tr>          
		</tbody>
	</table>
</body>
</html>

calculate distance between two usually is highly underestimated.

Especially due to Superimposed substitution, 


Superimposed substitutions ("multiple hits"): The occurrence of two or more substitutions at the same site

<html>
<head>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>Time</th>
				<th>N1</th>
				<th>N2</th>
				<th>N3</th>
				<th>N4</th>
				<th>N5</th>
				<th>N6</th>
				<th>N7</th>
				<th>N8</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#FC8D62;">C</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
			</tr>
			<tr>
				<td>2</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#FC8D62;">C</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
			</tr>
			<tr>
				<td>3</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
			</tr>
			<tr>
				<td>4</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
			</tr>
			<tr>
				<td>5</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
			</tr>
		</tbody>
	</table>
    
    
</body>
</html>

Critical to models of nucleotide evolution is the realization that because there are only four possible character states, it is expected that as genetic distance increases, some sites will undergo multiple superimposed substitutions.

In this case, some sites that have undergone change will have reverted to the state they were originally in.
To reliably reconstruct evolutionary relationships among divergent sequences, this expected reversion must be taken into account.
Simple measures of distance that do not take multiple substitutions into account are said to be uncorrected. Corrected distances use one of several models of sequence evolution to estimate the number of sites that have undergone multiple substitutions.
Uncorrected methods tend to underestimate genetic distance.



<html>
<head>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>Species</th>
				<th>N1</th>
				<th>N2</th>
				<th>N3</th>
				<th>N4</th>
				<th>N5</th>
				<th>N6</th>
				<th>N7</th>
				<th>N8</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Sp. 1</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#FC8D62;">C</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#E78AC3;">T</td>
			</tr>
			<tr>
				<td>Sp. 2</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#E78AC3;">T</td>
				<td style="background-color:#66C2A5;">A</td>
				<td style="background-color:#8DA0CB;">G</td>
				<td style="background-color:#66C2A5;">A</td>
			</tr>
		</tbody>
	</table>
    
    
</body>
</html>

Model asre important because they allow to correct to some extent the bias of underestimate differences when we are calculating distances between sequences froom observed data.44

show plot of expected vs observed. Here is where substitution models are important.



## Substitution models

Assumming that the sequences evolved under certain model. For example if all sites changed under the same probability or if some sites are more likely to change than others.  Based on these assumptions we can compare observed pattern against predicted expectations in each model and correct the distance.

They are Markov model 



 They have two parts:
 - Stationary distribution
 - Transition matrix


Based on these we can derive a formula to correct the distance bias, usally based in some known distribution, for example the  Poisson distribution.  
This distribution is conveneinte in some cases because it fits well where events are independents, continuous in time, and rare.

### Jukes-Cantor model

Basic model, proposed by Jukes and Cantor (1969)
It has 2 assumbtions
- This assumes that there is only one substitution rate and it is equal for all bases
- All frequencies for all bases are equal (in the stationary distribution) 

This model is also know as a one paremeter model, because the model only needs one parameter.

In [399]:
# Define the only parameter
rate = 0.333  # α (rate of substitution) 

In [387]:
# Transition matrix for Jukes-Cantor model
                 #  A        G     C     T
jc_tm = np.array([[1-3*rate, rate, rate, rate],  # A
                  [rate, 1-3*rate, rate, rate],  # G
                  [rate, rate, 1-3*rate, rate],  # C
                  [rate, rate, rate, 1-3*rate]   # T
                 ])

In [388]:
jc_tm

array([[0.001, 0.333, 0.333, 0.333],
       [0.333, 0.001, 0.333, 0.333],
       [0.333, 0.333, 0.001, 0.333],
       [0.333, 0.333, 0.333, 0.001]])

In [389]:
get_stationary_dist_expo("ACGT", iterations=100, transition_matrix=jc_tm)

array([0.25, 0.25, 0.25, 0.25])

In [397]:
plot_convergency(states="ACGT", initial_state="C", steps= 1000, transition_matrix=jc_tm);

<svg class="toyplot-canvas-Canvas" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="600px" height="600px" viewBox="0 0 600 600" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" id="t12fff087408c4d0b959bbf265d920ed3"> <path d="M 50.0 550.0 L 50.48606358489392 550.0 L 50.972127169787846 550.0 L 51.45819075468176 550.0 L 51.944254339575686 400.0 L 52.430317924469605 425.0 L 52.91638150936353 442.85714285714283 L 53.40244509425745 456.25 L 53.88850867915137 466.6666666666667 L 54.37457226404529 475.0 L 54.86063584893922 413.6363636363636 L 55.34669943383314 425.0 L 55.832763018727064 434.6153846153846 L 56.31882660362098 389.2857142857143 L 56.804890188514904 400.0 L 57.29095377340882 409.375 L 57.77701735830275 373.5294117647058 L 58.26308094319667 383.33333333333337 L 58.74914452809059 392.10526315789474 L 59.23520811298451 400.0 L 59.72127169787842 407.14285714285717 L 60.20733528277235 413.6363636363636 L 60.693398867666275 419.5652173913043 L 61.17946245256019 393.75 L 61.665526037454114 400.0 L 62.15158962234804 405.7692307692307 L 62.637653207241954 411.11111111111114 L 63.12371679213588 389.2857142857143 L 63.60978037702981 394.82758620689657 L 64.09584396192372 400.0 L 64.58190754681765 380.64516129032256 L 65.06797113171157 385.9375 L 65.55403471660549 368.1818181818182 L 66.04009830149941 373.5294117647058 L 66.52616188639333 378.5714285714286 L 67.01222547128725 383.33333333333337 L 67.49828905618118 387.8378378378378 L 67.98435264107509 392.10526315789474 L 68.47041622596902 396.15384615384613 L 68.95647981086293 400.0 L 69.44254339575686 385.36585365853654 L 69.92860698065078 389.2857142857143 L 70.4146705655447 375.58139534883725 L 70.90073415043862 379.54545454545456 L 71.38679773533255 383.33333333333337 L 71.87286132022646 386.95652173913044 L 72.35892490512039 374.468085106383 L 72.84498849001432 378.125 L 73.33105207490823 366.32653061224494 L 73.81711565980216 370.0 L 74.30317924469608 373.5294117647058 L 74.78924282959 376.9230769230769 L 75.27530641448391 366.0377358490566 L 75.76136999937785 369.4444444444444 L 76.24743358427176 359.09090909090907 L 76.73349716916567 362.5 L 77.2195607540596 365.7894736842105 L 77.70562433895353 368.9655172413793 L 78.19168792384744 359.32203389830505 L 78.67775150874137 362.5 L 79.1638150936353 353.27868852459017 L 79.6498786785292 356.45161290322585 L 80.13594226342313 359.5238095238095 L 80.62200584831706 362.5 L 81.10806943321097 365.38461538461536 L 81.5941330181049 356.8181818181818 L 82.08019660299883 359.7014925373134 L 82.56626018789274 351.47058823529414 L 83.05232377278666 354.34782608695656 L 83.53838735768059 346.4285714285714 L 84.0244509425745 349.29577464788736 L 84.51051452746842 352.0833333333333 L 84.99657811236236 354.7945205479452 L 85.48264169725627 347.29729729729723 L 85.96870528215018 350.0 L 86.4547688670441 352.63157894736844 L 86.94083245193804 355.19480519480527 L 87.42689603683195 348.07692307692304 L 87.91295962172589 350.6329113924051 L 88.3990232066198 343.74999999999994 L 88.88508679151371 346.2962962962963 L 89.37115037640764 339.6341463414634 L 89.85721396130157 342.16867469879514 L 90.34327754619548 335.7142857142857 L 90.8293411310894 338.235294117647 L 91.31540471598333 331.97674418604646 L 91.80146830087725 334.4827586206897 L 92.28753188577116 336.93181818181813 L 92.7735954706651 330.8988764044944 L 93.25965905555901 333.33333333333337 L 93.74572264045293 327.47252747252753 L 94.23178622534685 329.891304347826 L 94.71784981024078 332.25806451612897 L 95.20391339513469 334.57446808510633 L 95.68997698002863 336.8421052631579 L 96.17604056492254 339.0625 L 96.66210414981646 341.2371134020618 L 97.14816773471038 335.714

The formula to correct the distance is:
$$D = -\frac{3}{4}ln(1 - \frac{4}{3}d)$$

Where ***D*** is the corrected distance and ***d*** is the distance between two sequences

In [516]:
def get_distances_jc(sequences, pair=(0,1)):
    # tranform list of strings into arrays (useful to conect with random walk function)
    # and convert sequences in ascii values for easy diff calculation
    sequences_array = np.asarray([[ord(base) for base in sequence] for sequence in sequences])
    
    # simplify the alignment and only count the unique patterns (instead of sites) 
    # to calculate the likelihood of a given substitution
    patterns, pattern_frequencies = np.unique(sequences_array, axis=1, return_counts=True)
    
    # get differences
    differences = patterns[pair[0]] - patterns[pair[1]]
    # calculate the distance
    distance = np.count_nonzero(differences) / len(sequences[pair[0]])
    
    # correct distance using jc model
    corrected_distance = -3/4 * np.log(1 - 4/3 * distance)
    
    return corrected_distance, distance

In [521]:
# Simple definition of sequences
sequences = ["GCTTCTGATTAACCTGCT",
             "GCTTCTGATTTCTCTGCC",
]

In [522]:
get_distances_jc(sequences, (0, 1))

(0.2635484151284164, 0.2222222222222222)

Let's generate a sequence under Jukes-Cantor model

In [523]:
sequence = print_random_walk(states="ACGT", 
                  steps=1000, 
                  initial_state="C", 
                  transition_matrix=jc_tm)
sequence

'CTATAGCTCTGCGAGATGCATGTACGCTACATCTCTCTATAGCGCTAGATATCTGTACACATGATCTCTGCGCATACACTGACAGCTCTCGTGCAGCGCTCTGATGTATCATGTCGAGAGTGCGCTCTGACGACACTAGCGCACTAGTGTGCGCGCATGCATGAGTATCTCACTCTGTGATACGCAGTCATACTCACGACTCTGCGAGTATCTATGACGTATGTCTGTATCTCACATCTACACGCTATGATATGACTATGATACAGCGACTAGTCTGCTACGCGTGTATGTGCTAGAGCGCACGTCACTGTACGTACTCATCTCTCATGACATCACACAGTCTGAGTACTCTCATCATGAGCTATAGCTGCTAGCAGTACTGATCACGATGAGCAGCATCGTATAGCAGCATACTGACAGTGATGATATCACATGTCATCGTCGACAGCGATAGCTAGACATGTACTGCTCGAGAGCATATAGCTCAGCATATGCATGCTATCGATCATAGTCACACGCGCTACAGTGACAGAGACGTCTCAGCAGTGATCGCACTCTGACTCAGCTCAGAGCTGCTCGACATCAGTGTACGTGCAGTCAGAGCACGTATACTCATGCGCACACGATATGATGTCTACTCACGATCGCGTGATACATGTGACTCGCGTGATCGCGATGCGATGTGTGCATCGTGATCAGATAGTCAGTATAGCAGTCGCAGTAGCAGTGCGCATCGATGATGATAGCTACACGTCAGCTCGCAGTGCACTCAGCTACTACTATGCTCATATATAGCTCTACACGATAGCATCGACACTGAGTCGTGCTCACGTACTGACGTCTAGCAGAGCGCTCTACGCTACTGTGTATGTACGCTCTGACAGTGTATGACGACGCTACATACGCTCACACGCATGTGTAGACTCACGCGCTGCTATCACGCGACGTCTCATGAGTGTGTCTCACGCAGATACTGAGACTGACGACAGCTACGTCGCA

Now introduce a random mutation 

In [ ]:
for i in range(100):
    sequence

### Kimura 2 parameters models

### Gamma

### Invariant sites

# Archive

In [159]:
def get_probability_sequence(sequence, transition_matrix, stationary_distribution):
    initial_state = sequence[0]
    probability = pi[initial_state]
    previous_state = initial_state

    for i in range(1, len(sequence)):
        current_state = sequence[i]
        probability *= transition_matrix[previous_state][current_state]
        previous_state = current_state
        
    return probability

In [159]:
def get_probability_sequence(sequence, transition_matrix, stationary_distribution):
    initial_idx = 0
    probability = stationary_distribution[initial_idx]
    previous_state = sequence[initial_idx]

    for i in range(1, len(sequence)):
        current_state = sequence[i]
        probability *= transition_matrix[previous_state][current_state]
        previous_state = current_state
        
    return probability

In [ ]:
get_probability_sequence("ACCCCGGCCCCAAAGGGGGTATATAA", transition_matrix=transition_matrix, stationary_distribution=[0.25,0.25,0.25,0.25])

In [14]:
## comparing our distribution with a totally random sequence

In [ ]:
# The frequency of bases will be very different if the sequence that we have does fit into our markov model. For ecample

In [5]:
absolutly_random_sequence = "".join(np.random.choice(list("AGCT"), size=1000))
absolutly_random_sequence

'TTCAGTTCGATCGACAATACGTGGCTGTTACGCTTACGCGACGACAGTCTTACACAGGCACAAGTGCGTACGATCTGAGGCGTGGCATACGATCCTCGCGTGGGAGTGTACCGCGACTGATCGCCGCCAATCCTTTTAAGGCAGCGTGAGCTACCATATGACGGCGAAGGGGTAACATTCGTGTCGGACCGGTAATTTTGGATGGAGGACGTTGTCCGGTTTGGATAGTGGGACTTCGGGATGTTTACCACCGAACGTACTGACGAGGTCAGGGGAGTCGACTCAATATCAGAGGCGTACCTGATAAGGTTCCTACTACTCCTCGCGATTCCGGCGCAAAAGGATGTTCTAGGATAATGAATATTCTACCGGCAGCCGTGGACCGGTTGTCCGCATTTAGTAGATAGGGTGAATACATAACATAAGCCTCGTGGGGCCGCCCGGCGCTGAGTCACAGGCAAGGTAACTTAGTAGAGGGCGCGTGTGAACCCTGATCGATCGCGTGTTAGATCCGCCGGCGAGCGATATTCGGGCTAGATCATATGGACGCATTTGTTAACCGTTCGAGTCAGGGCCAAGAAGGTGGATCACATGTCGAGTTGTTTCATTTCGCCGACCCGTCTCAGCCGCAATGGCGAAAGCAAGGTGGTCTCGTGCGAGGCAGCGCCAAAAATCGGGTGGGACGACCCCTGGAACAATGTCGGGATGACATAAAACCAATTTAATGCCATACACGACGGCGCGAAGAGTTTGTGCAGCCCGCAATCGTATAAAAGGCCAGAAGCGTACGGCGTGATCCTGTTTGGTCACTATGCCCCATGCTTAGGGCGCACGCTTTTCCTCACCCGCTGGGAATACGGTATAAGCGCGCGAGCCCCCGCCGCGTTCTTAGGTCCCTAACTTAAGCTATTGCCCCCTGGATGAAGGGCGGTTCGTCACTTCTGTCCGGTCCCCTGGGCGCTTCATCTCCTACAGCATTTGGCTTCATGCGGGATCCCG

In [167]:
empiric_frequencies = {}
for base in "AGCT":
    empiric_frequencies[base] = absolutly_random_sequence.count(base) / len(absolutly_random_sequence)
    
empiric_frequencies  

{'A': 0.223, 'G': 0.291, 'C': 0.257, 'T': 0.229}

In [374]:

from __future__ import division
import math
import numpy as np

def JC69_Q():
    a = 0.01/3
    Q = np.asarray(
    [  -3*a, a, a, a,
       a, -3*a, a, a,
       a, a, -3*a, a,
       a, a, a, -3*a ])
    Q.shape = (4,4)
    return Q
    
def TN93_values():
    pi = [0.2,0.3,0.2,0.3]
    T,C,A,G = pi
    Y = T + C
    R = A + G
    a1 = 2   # Y transitions
    a2 = 1   # R transitions
    b = 0.2    # transversions
    return T,C,A,G,Y,R,a1,a2,b
    
def TN93_Q():
    T,C,A,G,Y,R,a1,a2,b = TN93_values()
    Q = np.asarray(
        [ -(a1*C + b*R), a1*C, b*A, b*G,
          a1*T, -(a1*T + b*R), b*A, b*G,
          b*T, b*C, -(a2*G + b*Y), a2*G,
          b*T, b*C, a2*A, -(a2*A + b*Y) ])
    Q.shape = (4,4)
    return Q
    
def TN93_P(t):
    # order TCAG
    T,C,A,G,Y,R,a1,a2,b = TN93_values()
    e2 = math.e**(-b*t)
    e3 = math.e**(-(R*a2 + Y*b)*t)
    e4 = math.e**(-(Y*a1 + R*b)*t)

    TY,CY,AR,GR = T/Y,C/Y,A/R,G/R
    M = [
        T + TY*R*e2 + CY*e4, C + CY*R*e2 - CY*e4,
        A*(1 - e2), G*(1 - e2),
        T + TY*R*e2 - TY*e4, C + CY*R*e2 + TY*e4,
        A*(1 - e2), G*(1 - e2),
        T*(1 - e2), C*(1 - e2),
        A + AR*Y*e2 + GR*e3, G + GR*Y*e2 - GR*e3,
        T*(1 - e2), C*(1 - e2),
        A + AR*Y*e2 - AR*e3, G + GR*Y*e2 + AR*e3  ]
    P = np.array(M)
    P.shape = (4,4)
    return P
        
def convert(Q,t,debug=False):
    if debug:
        print ('Q', '\n', Q)
    evals, evecs = np.linalg.eig(Q)
    if debug:
        print  ('evals', '\n', evals)
    L = np.diag([math.e**(k*t) for k in evals])
    if debug:
        print  ('L', '\n', L)
    U = evecs
    if debug:
        print  ('U', '\n', U)
    iU = np.linalg.inv(U)
    if debug:
        print  ('iU', '\n', iU)
    P = np.dot(U,np.dot(L,iU))
    if debug:
        print  ('P', '\n', P)
    return P
    
def long_time(P,N=5000):
    M = P
    for i in range(N):
        M = np.dot(P,M)
    return M

In [ ]:
convert(JC69_Q(), 10000, debug=True)

Q 
 [[-0.01        0.00333333  0.00333333  0.00333333]
 [ 0.00333333 -0.01        0.00333333  0.00333333]
 [ 0.00333333  0.00333333 -0.01        0.00333333]
 [ 0.00333333  0.00333333  0.00333333 -0.01      ]]
evals 
 [-1.33333333e-02  4.33680869e-19 -1.33333333e-02 -1.33333333e-02]
L 
 [[1.24184982e-58 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.24184982e-58 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.24184982e-58]]
U 
 [[-0.8660254   0.5        -0.2747774  -0.12962158]
 [ 0.28867513  0.5         0.7841548   0.40424231]
 [ 0.28867513  0.5         0.04519959 -0.76264153]
 [ 0.28867513  0.5        -0.55457698  0.4880208 ]]
iU 
 [[-0.8660254  -0.01093835  0.42842131  0.44854245]
 [ 0.5         0.5         0.5         0.5       ]
 [-0.          0.77008713 -0.05158606 -0.71850107]
 [-0.          0.36930849 -0.82431531  0.45500682]]
P 
 [[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])